# Generated by Django 5.0.6 on 2024-07-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('viewers', models.IntegerField()),
                ('organization', models.CharField(max_length=255)),
                ('liked', models.BooleanField(default=False)),
                ('totalLikes', models.IntegerField(default=0)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('source_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('group_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('udp_port', models.CharField(blank=True, max_length=255, null=True)),
                ('amt_relay', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
